language: ruby
rvm:
  - 2.2
  - jruby
  
script: bundle exec rspec

addons:
  code_climate:
    repo_token:
      secure: IAI69GTSB9d+g+GjqXqdoTmjttMNpmFi8krKP3anZnpA7nifmb7ULxsy+snQGJVM3lQXsZrPqoIiFn5g/MHkt3/EIVtUPJDnPxcx7zJPRNfmwucDvOWkxRm6WJPIzgz6/uO1o8VxSoM/BYXntUW8NgvHbHGSSqa6JRMBlr+suVw+4lb11TDIoLSps6A+aJbEuK15HbtmsVmAjMBWq+lLmCeNGNjSqEbvRk4Xb3ouyXFE2SzBmcC3GYlsXSnDgHZ6WRcmt63Z/41zAYLEuMjQUKda0hfp6UvczKsT/UvsbC98IpkDK5IG0kNAJORIMlTuT+ANCjMe2Jf8QjHHDmOtHGfnSg9r51BrQTRUJzJUTevuJlUj9OXIbCXOn5vB0iFmptpL4RehwQ9RKzLhpRBnwogIuQ0jKFzjtda2/0xFBmqS7fF5V3sSwaYM4U8j0fB9lyIy8cHg3fOzvRImKgQBqXqfsMvG4zupv6xCsi8TmVZEzovu+0tcOsVRBUlzQahsvdcfiDVFmv3af3KzMeMdrey/jkzVPcTtQiRtx8tlZ2zJU3TmAqJh5B1JPPfPnhTuZ8Uh4JtBwokTT8YC+wet4TJ7bxi1RBwdHRclAJFlG+0On97UpzSgQP79c0hA+d421k0JfcCaAcm5jrfK6qys4YMMqPXPH+c6aWlh6rXZ0D4=
